module.exports = {
    help: require('./help'),
    group: require('./group'),
    alias: require('./alias'),
    permission: require('./permission'),
    team: require('./team'),
    flowerPrice: require('./flowerPrice'),
    goldPrice: require('./goldPrice'),
    exam: require('./exam'),
    serverStatus: require('./serverStatus'),
    achievement: require('./achievement'),
    serendipity: require('./serendipity'),
    macro: require('./macro'),
    gameUpdate: require('./gameUpdate'),
    sandbox: require('./sandbox'),
    daily: require('./daily'),
    reinforcement: require('./reinforcement'),
    eye: require('./eye'),
    travel: require('./travel'),
    furniture: require('./furniture'),
    saohua: require('./saohua'),
    saohuav: require('./saohuav'),
    doutu: require('./doutu'),
    price: require('./price'),
    //jjc: require('./jjc'),
    seniority: require('./seniority'),
    
    item: require('./item'),
    //chat: require('./chat')
}