module.exports = {
    help: require('./help'),
    group: require('./group'),
    alias: require('./alias'),
    permission: require('./permission'),
    team: require('./team'),
    flowerprice: require('./flowerPrice'),
    goldprice: require('./goldPrice'),
    exam: require('./exam'),
    serverstatus: require('./serverStatus'),
    achievement: require('./achievement'),
    serendipity: require('./serendipity'),
    macro: require('./macro'),
    gameupdate: require('./gameUpdate'),
    sandbox: require('./sandbox'),
    daily: require('./daily'),
    reinforcement: require('./reinforcement'),
    eye: require('./eye'),
    travel: require('./travel'),
    furniture: require('./furniture'),
    saohua: require('./saohua'),
    price: require('./price')
}